name: Terraform CD

# #when git push successfully, this will run
# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tf apply on"
        required: true
        default: "dev"
        type: choice
        options:
          ##these options here can be used to load different blocks of yaml for different steps
          - dev
          - staging
          - prod

# declare the running agent
jobs:
  Terraform-CD:
    runs-on: ubuntu-latest

    steps:
      #git clone/ git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      #aws configure
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # or hardcode us-east-1

      #install terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      #terraform init
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform workspace list
        run: terraform workspace list

      - name: Terraform workspace new environment and select
        run: |
          terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}
          terraform workspace list

      # #terraform apply
      # - name: Terraform Apply
      #   run: terraform apply --auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"
      # # alternate manual way to reassign var
      # #   run: terraform apply --auto-approve -var 'abc="environments/${{ github.event.inputs.environment }}.tfvars"'

      # # Wait 10 minutes
      # - name: wait for 5min
      #   run: sleep 300

      # #terraform Destroy
      # - name: Terraform Destroy
      #   run: terraform Destroy --auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"

      #   is pods created once fail or always standby?
      #   previously without storagfe all in one is bad?
      #   where are these workspace record stored? in s3?
      #   if i  stop ec2 instance manually , will terraform apply delete the previous instacn
